name: on_push

on:
  push:
    branches:
      - "**" # run on all branches:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      #RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      # Set start time
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        # Install Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20
        # Run mvn test
      - name: Run tests with Maven
        run: mvn test
      - name: Collect build data
        if: always()
        run: |
          echo "TOTAL_DURATION=$(expr $(date +%s) - ${START_TIME})"
          ./resources/test_result_script.sh
