name: on_push

on:
  push:
    branches:
      - "**" # run on all branches:

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # Install Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20
        # Run mvn test
      - name: Run tests with maven
        run: mvn test
            # Handle remote server chromedriver
